# Generated by Django 4.0.3 on 2022-03-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
