# Generated by Django 4.0.3 on 2022-03-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0003_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
